/* Generated By:JJTree: Do not edit this line. ASTAction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTAction extends SWLNode {
  public ASTAction(int id) {
    super(id);
  }

  public ASTAction(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=694a993721ac2da20971426ebacb974e (do not edit this line) */
