/* Generated By:JJTree: Do not edit this line. ASTAction.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;


public class ASTAction extends SWLNode {

	private String returnType;


	public ASTAction(int id) {
		super(id);
	}


	public String getReturnType() {
		return this.returnType;
	}


	public void setReturnType(String returnType) {
		this.returnType = returnType;
	}


	public List<ASTActionParam> getActionParams() {
		return getChildNodesOfType(ASTActionParam.class, true);
	}

}
/*
 * JavaCC - OriginalChecksum=694a993721ac2da20971426ebacb974e (do not edit this
 * line)
 */
