/* Generated By:JJTree: Do not edit this line. ASTAppName.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTAppName extends SWLNode {

	public ASTAppName(int id) {
		super(id);
	}


	public ASTAppName(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=3c0eeae16e103296636b04aba7f6ec74 (do not edit this
 * line)
 */
