/* Generated By:JJTree: Do not edit this line. ASTActionParam.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.SWLNode;

public class ASTActionParam extends SWLNode {

	private String name;
	private ASTType type;


	public ASTActionParam(int id) {
		super(id);
	}


	public void setName(String image) {
		this.name = image;
	}


	public String getName() {
		return name;
	}



	public void setType(ASTType t1) {
		this.type = t1;
	}


	public ASTType getType() {
		return type;
	}


	public String getTypeAsString() {
		if (type == null) {
			return null;
		}

		return type.getTypeName();
	}



}
/*
 * JavaCC - OriginalChecksum=e9b4b11ebf888d6b8bd048f2a8ff4e69 (do not edit this
 * line)
 */
