/* Generated By:JJTree: Do not edit this line. ASTButtonGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTButtonGroup extends ro.swl.engine.parser.model.SWLNode {
  public ASTButtonGroup(int id) {
    super(id);
  }

  public ASTButtonGroup(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=779a2c8dc8e179f064b18710791a19f8 (do not edit this line) */
