/* Generated By:JJTree: Do not edit this line. ASTButtonGroup.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import static ro.swl.engine.parser.SWLConstants.BUTTONGROUP;
import static ro.swl.engine.parser.SWLConstants.tokenImage;
import ro.swl.engine.parser.model.Component;


public class ASTButtonGroup extends Component {

	public ASTButtonGroup(int id) {
		super(id);
		setImageWithoutQuote(tokenImage[BUTTONGROUP]);
	}


	@Override
	protected String getComponentName() {
		return "button_group";
	}

}
/*
 * JavaCC - OriginalChecksum=7f02ebf906af6f3182dce9620ed84e8d (do not edit this
 * line)
 */
