/* Generated By:JJTree: Do not edit this line. ASTButton.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;

import static ro.swl.engine.parser.SWLConstants.BUTTON;
import static ro.swl.engine.parser.SWLConstants.tokenImage;


public class ASTButton extends Component {

	public ASTButton(int id) {
		super(id);
		setImageWithoutQuote(tokenImage[BUTTON]);
		addClass(grammar.buttonClassAttribute());
	}


	@Override
	protected String getComponentName() {
		return grammar.button();
	}



	public ASTButtonAction getAction() {
		ASTButtonAction bAction = getChildNodesOfType(ASTButtonAction.class, true).get(0);
		return bAction;
	}

}
/*
 * JavaCC - OriginalChecksum=bd762770e8fb8dd1aa87f708405b1c81 (do not edit this
 * line)
 */
