/* Generated By:JJTree: Do not edit this line. ASTCssStyleName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTCssStyleName extends ro.swl.engine.parser.model.SWLNode {
  public ASTCssStyleName(int id) {
    super(id);
  }

  public ASTCssStyleName(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56ced53227e6ad3a2322ee9a3b5e0b98 (do not edit this line) */
