/* Generated By:JJTree: Do not edit this line. ASTController.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTController extends SWLNode {

	public ASTController(int id) {
		super(id);
	}


	public ASTController(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=a9020f1421b74bcc508209d13943eeff (do not edit this
 * line)
 */
