/* Generated By:JJTree: Do not edit this line. ASTCssStyleValue.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;


public class ASTCssStyleValue extends SWLNode {

	public ASTCssStyleValue(int id) {
		super(id);
	}


	public ASTCssStyleValue(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=25f0c95a8076c77102edbea34ef4ff70 (do not edit this
 * line)
 */
