/* Generated By:JJTree: Do not edit this line. ASTCssStyle.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTCssStyle extends ro.swl.engine.parser.model.SWLNode {
  public ASTCssStyle(int id) {
    super(id);
  }

  public ASTCssStyle(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2d62a54eb2bc3eecfd0b25a4dcc835b9 (do not edit this line) */
