/* Generated By:JJTree: Do not edit this line. ASTEnum.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;


public class ASTEnum extends SWLNode {

	public ASTEnum(int id) {
		super(id);
	}


	public String getName() {
		return getImage();
	}


	public List<ASTEnumLiteral> getLiterals() {
		return getChildNodesOfType(ASTEnumLiteral.class, true);
	}

}
/*
 * JavaCC - OriginalChecksum=a71eb2425c996b88b0719cdee2862f30 (do not edit this
 * line)
 */
