/* Generated By:JJTree: Do not edit this line. ASTEnumLiteral.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTEnumLiteral extends SWLNode {

	public ASTEnumLiteral(int id) {
		super(id);
	}


	public String getName() {
		return getImage();
	}

}
/*
 * JavaCC - OriginalChecksum=4eef6bef662582637c9a5258732a7f8d (do not edit this
 * line)
 */
