/*
 * Generated By:JJTree: Do not edit this line. ASTExternalInterface.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;


public class ASTExternalInterface extends SWLNode {

	private String type;

	private String name;


	public ASTExternalInterface(int id) {
		super(id);
	}


	public List<ASTServiceActions> getChildServiceActions() {
		return getChildNodesOfType(ASTServiceActions.class, true);
	}


	public String getType() {
		return type;
	}



	public void setType(String type) {
		this.type = type;
	}



	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}


	public List<ASTAction> getCustomActions() {
		return getChildNodesOfType(ASTAction.class, false);
	}
}
/*
 * JavaCC - OriginalChecksum=53cad5d11f300764b062f73f7f428a48 (do not edit this
 * line)
 */
