/* Generated By:JJTree: Do not edit this line. ASTExchangeModel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTExchangeModel extends SWLNode {
  public ASTExchangeModel(int id) {
    super(id);
  }

  public ASTExchangeModel(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=53d3ab3e0a012632be1056ba88d69732 (do not edit this line) */
