/* Generated By:JJTree: Do not edit this line. ASTEntity.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;


public class ASTEntity extends SWLNode {


	public ASTEntity(int id) {
		super(id);
	}


	public String getName() {
		return getImage();
	}



	public List<ASTProperty> getFields() {
		return getChildNodesOfType(ASTProperty.class, true);
	}


	public ASTProperty getFieldWithName(String fieldName) {
		for (ASTProperty prop : getFields()) {
			if (prop.getName().equals(fieldName)) {
				return prop;
			}
		}
		return null;
	}


	public ASTProperty getFieldWithType(String fieldType) {
		for (ASTProperty prop : getFields()) {
			if (prop.getType().equals(fieldType)) {
				return prop;
			}
		}
		return null;
	}


	@Override
	public String toString() {
		return getImage();
	}


}
/*
 * JavaCC - OriginalChecksum=dc6c9095c451eb08d7a033ab117ee321 (do not edit this
 * line)
 */
