/* Generated By:JJTree: Do not edit this line. ASTGenericBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTGenericBlock extends ro.swl.engine.parser.model.SWLNode {
  public ASTGenericBlock(int id) {
    super(id);
  }

  public ASTGenericBlock(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c52faa3a6c0e6d73a7b6e92fa4ebd869 (do not edit this line) */
