/*
 * Generated By:JJTree: Do not edit this line. ASTHorizontalLayout.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import static ro.swl.engine.parser.SWLConstants.HORIZONTAL_LAYOUT;
import static ro.swl.engine.parser.SWLConstants.tokenImage;

import java.util.ArrayList;
import java.util.List;

import ro.swl.engine.parser.model.Component;
import ro.swl.engine.parser.model.LayoutComponent;


public class ASTHorizontalLayout extends LayoutComponent {

	public ASTHorizontalLayout(int id) {
		super(id);
		setImageWithoutQuote(tokenImage[HORIZONTAL_LAYOUT]);
		addClass(grammar.horizontalLayoutClass());
	}


	public List<ASTLayoutColumn> getColumns() {
		return getChildNodesOfType(ASTLayoutColumn.class, false);
	}


	@Override
	public List<Component> getChildComponents() {
		return new ArrayList<Component>(getColumns());
	}


	@Override
	protected String getComponentName() {
		return grammar.horizontalLayout();
	}

}
/*
 * JavaCC - OriginalChecksum=ca22731bbbdc3c566291c82b1e7bd3d2 (do not edit this
 * line)
 */
