/* Generated By:JJTree: Do not edit this line. ASTInputArea.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import static ro.swl.engine.parser.SWLConstants.INPUT_AREA;
import static ro.swl.engine.parser.SWLConstants.tokenImage;
import ro.swl.engine.parser.model.InputComponent;


public class ASTInputArea extends InputComponent {

	public ASTInputArea(int id) {
		super(id);
		setImageWithoutQuote(tokenImage[INPUT_AREA]);
	}


	@Override
	protected String getComponentName() {
		return grammar.inputArea();
	}


	@Override
	protected String getInputComponentType() {
		return grammar.inputAreaType();
	};

}
/*
 * JavaCC - OriginalChecksum=2e0487bc0772e10b5ad3fca5e8020f9f (do not edit this
 * line)
 */
