/* Generated By:JJTree: Do not edit this line. ASTInputFile.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.InputComponent;

import static ro.swl.engine.parser.SWLConstants.INPUT_FILE;
import static ro.swl.engine.parser.SWLConstants.tokenImage;


public class ASTInputFile extends InputComponent {

	public ASTInputFile(int id) {
		super(id);
		setImageWithoutQuote(tokenImage[INPUT_FILE]);
	}


	@Override
	protected String getComponentName() {
		return grammar.inputFile();
	}


	@Override
	protected String getInputComponentType() {
		return grammar.inputFileType();
	}

}
/*
 * JavaCC - OriginalChecksum=4d25d16b23b379a8fb8e70293e4e03da (do not edit this
 * line)
 */
