/* Generated By:JJTree: Do not edit this line. ASTLogic.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;


public class ASTLogic extends SWLNode {

	public ASTLogic(int id) {
		super(id);
	}


	public ASTLogic(SWL p, int id) {
		super(p, id);
	}


	public List<ASTService> getServices() {
		return getChildNodesOfType(ASTService.class, false);
	}


	public List<ASTExternalInterface> getExternalInterfaces() {
		return getChildNodesOfType(ASTExternalInterface.class, false);
	}

}
/*
 * JavaCC - OriginalChecksum=c4e39a15c74d56b2d11d4c978808de12 (do not edit this
 * line)
 */
