/* Generated By:JJTree: Do not edit this line. ASTModelVariable.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.SWLNode;

public class ASTModelVariable extends SWLNode {

	private boolean isLiteral;


	public ASTModelVariable(int id) {
		super(id);
	}


	public ASTModelVariable(SWL p, int id) {
		super(p, id);
	}


	public boolean isLiteral() {
		return isLiteral;
	}


	public void setLiteral(boolean isLiteral) {
		this.isLiteral = isLiteral;
	}

}
/*
 * JavaCC - OriginalChecksum=5c2aea81e4209deae297adfa20a92135 (do not edit this
 * line)
 */
