/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;


public class ASTModule extends SWLNode {

	public ASTModule(int id) {
		super(id);
	}


	public String getName() {
		return getFirstChildNodeOfType(ASTModuleName.class, true).getImage();
	}


	public ASTLogic getLogic() {
		return getFirstChildNodeOfType(ASTLogic.class, true);
	}


	public ASTDomain getDomain() {
		return getFirstChildNodeOfType(ASTDomain.class, true);
	}


	public ASTEntity findEntity(String fieldCls) {
		for (ASTEntity entity : getDomain().getEntities()) {
			if (entity.getName().equals(fieldCls)) {
				return entity;
			}
		}
		return null;
	}


	public int countEntities(String name) {
		int count = 0;
		for (ASTEntity entity : getDomain().getEntities()) {
			if (entity.getName().equals(name)) {
				count++;
			}
		}
		return count;
	}


	public ASTService findService(String serviceName) {
		List<ASTService> services = getChildNodesOfType(ASTService.class, true);
		for (ASTService service : services) {
			if (service.getImage().equals(serviceName)) {
				return service;
			}
		}
		return null;
	}

}
/*
 * JavaCC - OriginalChecksum=578759df104a0e372bd620814e0e8d33 (do not edit this
 * line)
 */
