/* Generated By:JJTree: Do not edit this line. ASTModuleName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTModuleName extends ro.swl.engine.parser.model.SWLNode {
  public ASTModuleName(int id) {
    super(id);
  }

  public ASTModuleName(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e7d6721f74870788f28a6c215324092a (do not edit this line) */
