/* Generated By:JJTree: Do not edit this line. ASTProperty.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTProperty extends SWLNode {

	private String name;

	private String type;

	private boolean owning;


	public ASTProperty(int id) {
		super(id);
	}


	public String getName() {
		return name;
	}



	public void setName(String name) {
		this.name = name;
	}



	public String getType() {
		return type;
	}



	public void setType(String type) {
		this.type = type;
	}



	public boolean isOwning() {
		return owning;
	}



	public void setOwning(boolean owning) {
		this.owning = owning;
	}


}
/*
 * JavaCC - OriginalChecksum=df6e5e061ca05073cb1da58c196fce0e (do not edit this
 * line)
 */