/* Generated By:JJTree: Do not edit this line. ASTService.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.SWLNode;

import java.util.List;


public class ASTService extends SWLNode {

	public ASTService(int id) {
		super(id);
	}


	public List<ASTAction> getActions() {
		return getChildNodesOfType(ASTAction.class, true);
	}

    public List<ASTCrud> getCruds() {
        return getChildNodesOfType(ASTCrud.class, true);
    }
}
/*
 * JavaCC - OriginalChecksum=10d537bca4f4e38e6a4bafec49a9cdc0 (do not edit this
 * line)
 */
