/* Generated By:JJTree: Do not edit this line. ASTSearcher.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTSearcher extends SWLNode {

	private String entity;
	private String searcherName;
	private String query;


	public ASTSearcher(int id) {
		super(id);
	}


	public void setEntity(String image) {
		this.entity = image;
	}


	public void setSearcherName(String image) {
		this.searcherName = image;
	}


	public void setQuery(String image) {
		this.query = image;
	}


	public String getEntity() {
		return entity;
	}



	public String getSearcherName() {
		return searcherName;
	}



	public String getQuery() {
		return query;
	}


}
/*
 * JavaCC - OriginalChecksum=c0fa90a7a39c2450d0feb3c2f2ac05da (do not edit this
 * line)
 */
