/*
 * Generated By:JJTree: Do not edit this line. ASTServiceActions.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTServiceActions extends SWLNode {

	public ASTServiceActions(int id) {
		super(id);
	}


	public ASTServiceActions(SWL p, int id) {
		super(p, id);
	}


	public String getReferencedServiceName() {
		return getImage();
	}

}
/*
 * JavaCC - OriginalChecksum=8dc168405633bfde4e75f24e8b926d0d (do not edit this
 * line)
 */
