/* Generated By:JJTree: Do not edit this line. ASTScreen.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTScreen extends SWLNode {

	public ASTScreen(int id) {
		super(id);
	}


	public ASTScreen(SWL p, int id) {
		super(p, id);
	}
}
/*
 * JavaCC - OriginalChecksum=1339a89389f2f4cfd1a4962b4a044709 (do not edit this
 * line)
 */
