/* Generated By:JJTree: Do not edit this line. ASTSearcher.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import static org.apache.commons.lang3.StringUtils.remove;


public class ASTSearcher extends SWLNode {

	private String searcherName;
	private String query;


	public ASTSearcher(int id) {
		super(id);
	}


	public void setSearcherName(String image) {
		this.searcherName = image;
		setImage(image);
	}


	public void setQuery(String image) {
		if (image == null)
			return;

		this.query = remove(image, '"').replace("'", "");
	}



	public String getSearcherName() {
		return searcherName;
	}



	public String getQuery() {
		return query;
	}


}
/*
 * JavaCC - OriginalChecksum=c0fa90a7a39c2450d0feb3c2f2ac05da (do not edit this
 * line)
 */
