/*
 * Generated By:JJTree: Do not edit this line. ASTSelectboxOptions.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

public class ASTSelectboxOptions extends SWLNode {

	public ASTSelectboxOptions(int id) {
		super(id);
	}


	public ASTSelectboxOptions(SWL p, int id) {
		super(p, id);
	}
}
/*
 * JavaCC - OriginalChecksum=47efd50d16c68adf7425760541c64254 (do not edit this
 * line)
 */
