/* Generated By:JJTree: Do not edit this line. ASTSection.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.LayoutComponent;
import ro.swl.engine.writer.ui.TagWriter;
import ro.swl.engine.writer.ui.WriteException;

import static ro.swl.engine.parser.SWLConstants.SECTION;
import static ro.swl.engine.parser.SWLConstants.tokenImage;


public class ASTSection extends LayoutComponent {

	public ASTSection(int id) {
		super(id);
		setImageWithoutQuote(tokenImage[SECTION]);
	}


	@Override
	protected String getComponentName() {
		return grammar.section();
	}


	@Override
	public ASTModelVariable getModelValueBinding() {
		return getFirstChildNodeOfType(ASTModelVariable.class, true);
	}


	@Override
	protected void renderContentBeforeChildren(TagWriter writer) throws WriteException {
		writer.startTag(grammar.sectionTitle());
		writer.endTag(false);
		writer.append("legend label TODO");
		writer.closeTag(grammar.sectionTitle(), true);
	}

}
/*
 * JavaCC - OriginalChecksum=6b3aa65a2918073fff74fff9cc56e700 (do not edit this
 * line)
 */
