/* Generated By:JJTree: Do not edit this line. ASTSelectOptionGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTSelectOptionGroup extends ro.swl.engine.parser.model.SWLNode {
  public ASTSelectOptionGroup(int id) {
    super(id);
  }

  public ASTSelectOptionGroup(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f74c92fbe7b935f536a4d86dbca8a23d (do not edit this line) */
