/* Generated By:JavaCC: Do not edit this line. SWLTreeConstants.java Version 5.0 */
package ro.swl.engine.parser;

public interface SWLTreeConstants
{
  public int JJTSWDLAPP = 0;
  public int JJTNAMEDECL = 1;
  public int JJTAPPNAME = 2;
  public int JJTMODULE = 3;
  public int JJTMODULENAME = 4;
  public int JJTMODULEBODY = 5;
  public int JJTUI = 6;
  public int JJTSCREEN = 7;
  public int JJTSCREENNAME = 8;
  public int JJTMODEL = 9;
  public int JJTCONTROLLER = 10;
  public int JJTGENERICBLOCK = 11;
  public int JJTMVCAREA = 12;
  public int JJTVERTICALLAYOUT = 13;
  public int JJTHORIZONTALLAYOUT = 14;
  public int JJTLAYOUTCOLUMN = 15;
  public int JJTCOLUMNDESCRIPTION = 16;
  public int JJTHORIZONTALFORM = 17;
  public int JJTHORIZONTALFORMROW = 18;
  public int JJTLAYOUTROW = 19;
  public int JJTSECTION = 20;
  public int JJTINPUT = 21;
  public int JJTINPUTFILE = 22;
  public int JJTINPUTAREA = 23;
  public int JJTCHECKBOX = 24;
  public int JJTSELECTBOX = 25;
  public int JJTRADIO = 26;
  public int JJTRADIOS = 27;
  public int JJTTEXT = 28;
  public int JJTLABEL = 29;
  public int JJTIMG = 30;
  public int JJTBUTTONGROUP = 31;
  public int JJTBUTTON = 32;
  public int JJTBUTTONDESCRIPTION = 33;
  public int JJTBUTTONACTION = 34;
  public int JJTBUTTONACTIONPARAMETER = 35;
  public int JJTMODELVARIABLE = 36;
  public int JJTSTDLAYOUTDESCRIPTION = 37;
  public int JJTRADIOINPUTDESCRIPTION = 38;
  public int JJTRADIOSINPUTDESCRIPTION = 39;
  public int JJTSELECTINPUTDESCRIPTION = 40;
  public int JJTSELECTBOXOPTIONS = 41;
  public int JJTSELECTOPTION = 42;
  public int JJTSELECTOPTIONGROUP = 43;
  public int JJTSTDINPUTDESCRIPTION = 44;
  public int JJTCSSSTYLE = 45;
  public int JJTCSSCLASSNAME = 46;
  public int JJTCSSINLINESTYLE = 47;
  public int JJTCSSSTYLENAME = 48;
  public int JJTCSSSTYLEVALUE = 49;
  public int JJTLOGIC = 50;
  public int JJTSERVICE = 51;
  public int JJTCRUD = 52;
  public int JJTSEARCHER = 53;
  public int JJTACTION = 54;
  public int JJTACTIONPARAM = 55;
  public int JJTDOMAIN = 56;
  public int JJTENUM = 57;
  public int JJTENUMLITERAL = 58;
  public int JJTENTITY = 59;
  public int JJTPROPERTY = 60;


  public String[] jjtNodeName = {
    "SwdlApp",
    "NameDecl",
    "AppName",
    "Module",
    "ModuleName",
    "ModuleBody",
    "Ui",
    "Screen",
    "ScreenName",
    "Model",
    "Controller",
    "GenericBlock",
    "MvcArea",
    "VerticalLayout",
    "HorizontalLayout",
    "LayoutColumn",
    "ColumnDescription",
    "HorizontalForm",
    "HorizontalFormRow",
    "LayoutRow",
    "Section",
    "Input",
    "InputFile",
    "InputArea",
    "Checkbox",
    "Selectbox",
    "Radio",
    "Radios",
    "Text",
    "Label",
    "Img",
    "ButtonGroup",
    "Button",
    "ButtonDescription",
    "ButtonAction",
    "ButtonActionParameter",
    "ModelVariable",
    "StdLayoutDescription",
    "RadioInputDescription",
    "RadiosInputDescription",
    "SelectInputDescription",
    "SelectboxOptions",
    "SelectOption",
    "SelectOptionGroup",
    "StdInputDescription",
    "CssStyle",
    "CssClassName",
    "CssInlineStyle",
    "CssStyleName",
    "CssStyleValue",
    "Logic",
    "Service",
    "Crud",
    "Searcher",
    "Action",
    "ActionParam",
    "Domain",
    "Enum",
    "EnumLiteral",
    "Entity",
    "Property",
  };
}
/* JavaCC - OriginalChecksum=4e21a550bf69eb2aa68b84e58f85726f (do not edit this line) */
