/* Generated By:JJTree: Do not edit this line. ASTButtonAction.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;


public class ASTButtonAction extends SWLNode {
	public ASTButtonAction(int id) {
		super(id);
	}

	public ASTButtonAction(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=d8866867d98ce65856df54a1a6dcbdb2 (do not edit this
 * line)
 */
