/* Generated By:JJTree: Do not edit this line. ASTBr.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;
import ro.swl.engine.writer.WriteException;
import ro.swl.engine.writer.Writer;

public class ASTBr extends Component {
	public ASTBr(int id) {
		super(id);
	}

	public ASTBr(SWL p, int id) {
		super(p, id);
	}

	@Override
	public void beginBodyDeclaration(Writer writer) throws WriteException {
		writer.append("<br />");
	}

}
/*
 * JavaCC - OriginalChecksum=9f902c2c59a8127f6f3234e776076b87 (do not edit this
 * line)
 */
