/* Generated By:JJTree: Do not edit this line. ASTCssClassName.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.SWLNode;

public class ASTCssClassName extends SWLNode {
	public ASTCssClassName(int id) {
		super(id);
	}

	public ASTCssClassName(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=b56c72992d3ebc0248144b21fe130661 (do not edit this
 * line)
 */
