/*
 * Generated By:JJTree: Do not edit this line. ASTCssInlineStyle.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;


public class ASTCssInlineStyle extends SWLNode {
	public ASTCssInlineStyle(int id) {
		super(id);
	}

	public ASTCssInlineStyle(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=0cbb680a533f956d870fad11167db604 (do not edit this
 * line)
 */
