/*
 * Generated By:JJTree: Do not edit this line. ASTColumnDescription.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Description;

public class ASTColumnDescription extends Description {
	public ASTColumnDescription(int id) {
		super(id);
	}

	public ASTColumnDescription(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=99b9fded14529d453bbddc28c3ad4fab (do not edit this
 * line)
 */
