/* Generated By:JJTree: Do not edit this line. ASTDomain.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTDomain extends SimpleNode {
  public ASTDomain(int id) {
    super(id);
  }

  public ASTDomain(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8c4219fc7cae1fcb277d77175d60ad7 (do not edit this line) */
