/* Generated By:JJTree: Do not edit this line. ASTGenericBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTGenericBlock extends SimpleNode {
  public ASTGenericBlock(int id) {
    super(id);
  }

  public ASTGenericBlock(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b4f1aee82a18d519f0a59a4f9244bb1e (do not edit this line) */
