/* Generated By:JJTree: Do not edit this line. ASTH1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTH1 extends SWLNode {
  public ASTH1(int id) {
    super(id);
  }

  public ASTH1(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b732cce59a1e9541c34bb60794b2b5dd (do not edit this line) */
