/*
 * Generated By:JJTree: Do not edit this line. ASTHorizontalFormGroup.java
 * Version 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;

public class ASTHorizontalFormGroup extends Component {
	public ASTHorizontalFormGroup(int id) {
		super(id);
	}

	public ASTHorizontalFormGroup(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=127ca299977613e1125329c39272e672 (do not edit this
 * line)
 */
