/* Generated By:JJTree: Do not edit this line. ASTH5.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTH5 extends SimpleNode {
  public ASTH5(int id) {
    super(id);
  }

  public ASTH5(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=df48490e17a87ec1a88a6a799bed9029 (do not edit this line) */
