/* Generated By:JJTree: Do not edit this line. ASTH3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTH3 extends SWLNode {
  public ASTH3(int id) {
    super(id);
  }

  public ASTH3(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3a3550598bb58050e5a52af58185ad8b (do not edit this line) */
