/*
 * Generated By:JJTree: Do not edit this line. ASTHorizontalLayout.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;

public class ASTHorizontalLayout extends Component {
	public ASTHorizontalLayout(int id) {
		super(id);
	}

	public ASTHorizontalLayout(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=ca22731bbbdc3c566291c82b1e7bd3d2 (do not edit this
 * line)
 */
