/* Generated By:JJTree: Do not edit this line. ASTH4.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTH4 extends SWLNode {
  public ASTH4(int id) {
    super(id);
  }

  public ASTH4(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9fa28ec6840cb8bc79bc0fbad013124b (do not edit this line) */
