/* Generated By:JJTree: Do not edit this line. ASTH5.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTH5 extends SWLNode {
  public ASTH5(int id) {
    super(id);
  }

  public ASTH5(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3bbd440db0f2ea2623b376141ba578f9 (do not edit this line) */
