/* Generated By:JJTree: Do not edit this line. ASTH6.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTH6 extends SWLNode {
  public ASTH6(int id) {
    super(id);
  }

  public ASTH6(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0552f421b1c7389bc94ae7e353069c55 (do not edit this line) */
