/*
 * Generated By:JJTree: Do not edit this line. ASTHorizontalForm.java Version
 * 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;
import ro.swl.engine.parser.model.LayoutComponent;
import ro.swl.engine.writer.TagWriter;
import ro.swl.engine.writer.WriteException;

public class ASTHorizontalForm extends LayoutComponent {
	public ASTHorizontalForm(int id) {
		super(id);
	}

	@Override
	protected String getComponentName() {
		return grammar.horizontalLayout();
	}

	@Override
	protected boolean renderContentBeforeChild(TagWriter writer, Component child) throws WriteException {

		new ASTLabel(0).render(writer);
		ASTVerticalLayoutRow row = new ASTVerticalLayoutRow(0);
		row.jjtAddChild(child, 0);
		row.render(writer);
		return false;
	}

}
/*
 * JavaCC - OriginalChecksum=2277b458906837bffe5800588f4c22ac (do not edit this
 * line)
 */
