/*
 * Generated By:JJTree: Do not edit this line.
 * ASTHorizontalLayoutDescription.java Version 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;

import ro.swl.engine.parser.model.Description;

public class ASTHorizontalLayoutDescription extends Description {
	public ASTHorizontalLayoutDescription(int id) {
		super(id);
	}

	public ASTHorizontalLayoutDescription(SWL p, int id) {
		super(p, id);
	}

	/**
	 * returns block level css styles
	 */
	@Override
	public List<String> getCssClassNames() {
		return super.getCssClassNames();
	}

	public List<String> getCssClassNames(int columnNo) {
		Class<ASTCssClassName> cssCls = ASTCssClassName.class;
		Class<ASTColumnDescription> parentClass = ASTColumnDescription.class;
		return getImageOfChildNodesWithParentOfType(cssCls, parentClass);
	}

	@Override
	public List<String> getCssInlineStyles() {
		return super.getCssInlineStyles();
	}

	public List<String> getCssInlineStyles(int columnNo) {
		Class<ASTCssInlineStyle> cssCls = ASTCssInlineStyle.class;
		Class<ASTColumnDescription> parentClass = ASTColumnDescription.class;
		return getImageOfChildNodesWithParentOfType(cssCls, parentClass);
	}

}
/*
 * JavaCC - OriginalChecksum=b8a405287551ad69395e908d32d34eef (do not edit this
 * line)
 */
