/* Generated By:JJTree: Do not edit this line. ASTImg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTImg extends SimpleNode {
  public ASTImg(int id) {
    super(id);
  }

  public ASTImg(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eac04883f8f2e28e29668789136f950c (do not edit this line) */
