/* Generated By:JJTree: Do not edit this line. ASTInput.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;
import ro.swl.engine.writer.WriteException;
import ro.swl.engine.writer.Writer;

public class ASTInput extends Component {

	public ASTInput(int id) {
		super(id);
	}

	public ASTInput(SWL p, int id) {
		super(p, id);
	}

	@Override
	public void beginBodyDeclaration(Writer writer) throws WriteException {
		writer.appendLine(grammar.input());
	}

	@Override
	public void endBodyDeclaration(Writer writer) throws WriteException {
		writer.append(grammar.inputDeclarationEnd());
	}

	@Override
	public void endBody(Writer writer) throws WriteException {
		writer.append(grammar.inputEnd());
	}

	@Override
	public void writeLabel(Writer writer) throws WriteException {
		writer.appendLine(grammar.label());
		writer.append(grammar.labelDeclarationEnd());
		writer.append("input TODO");
		writer.append(grammar.labelEnd());
		labelRendered = true;
	}
}
/*
 * JavaCC - OriginalChecksum=eedb51c9abcc9e42e4fac7989a097346 (do not edit this
 * line)
 */
