/* Generated By:JJTree: Do not edit this line. ASTImg.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTImg extends SWLNode {
  public ASTImg(int id) {
    super(id);
  }

  public ASTImg(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ae3cbe4e6d8de1aa5a1c5b3011d2466f (do not edit this line) */
