/* Generated By:JJTree: Do not edit this line. ASTInputFile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTInputFile extends SimpleNode {
  public ASTInputFile(int id) {
    super(id);
  }

  public ASTInputFile(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1b15ea8ecce321c27f60e17101a5a03d (do not edit this line) */
