/* Generated By:JJTree: Do not edit this line. ASTInputArea.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTInputArea extends SimpleNode {
  public ASTInputArea(int id) {
    super(id);
  }

  public ASTInputArea(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b652436ebf3388aedd7802b8bd09cafb (do not edit this line) */
