/* Generated By:JJTree: Do not edit this line. ASTLabel.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;

public class ASTLabel extends Component {
	public ASTLabel(int id) {
		super(id);
	}

	public ASTLabel(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=513c8d374ad5a1445d78cade846b2e99 (do not edit this
 * line)
 */
