/* Generated By:JJTree: Do not edit this line. ASTLabel.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTLabel extends SimpleNode {
  public ASTLabel(int id) {
    super(id);
  }

  public ASTLabel(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=60ba50c4edd4712ee93b716af40c9f66 (do not edit this line) */
