/* Generated By:JJTree: Do not edit this line. ASTModelVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTModelVariable extends SimpleNode {
  public ASTModelVariable(int id) {
    super(id);
  }

  public ASTModelVariable(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=127b3d7613b45c48891a4081be7bb142 (do not edit this line) */
