/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTModule extends SWLNode {
  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=578759df104a0e372bd620814e0e8d33 (do not edit this line) */
