/* Generated By:JJTree: Do not edit this line. ASTMvcArea.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTMvcArea extends SWLNode {
  public ASTMvcArea(int id) {
    super(id);
  }

  public ASTMvcArea(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=62571ca9d46169c6493b96bcf95831a6 (do not edit this line) */
