/* Generated By:JJTree: Do not edit this line. ASTModuleBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTModuleBody extends SWLNode {
  public ASTModuleBody(int id) {
    super(id);
  }

  public ASTModuleBody(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2701ff9258959d6a4a1b3a1c6363257a (do not edit this line) */
