/* Generated By:JJTree: Do not edit this line. ASTRadio.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;
import ro.swl.engine.writer.WriteException;
import ro.swl.engine.writer.Writer;

public class ASTRadio extends Component {
	public ASTRadio(int id) {
		super(id);
	}

	public ASTRadio(SWL p, int id) {
		super(p, id);
	}

	@Override
	public void beginBodyDeclaration(Writer writer) throws WriteException {
		writer.appendLine(grammar.label());
		writer.append(grammar.styleClassAttribute(grammar.radioClass()));
		writer.append(grammar.labelDeclarationEnd());
		writer.indent();
		writer.appendLine(grammar.radio());
		writer.unIndent();
	}

	@Override
	public void endBodyDeclaration(Writer writer) throws WriteException {
		writer.append(grammar.radioDeclarationEnd());
	}

	@Override
	public void endBody(Writer writer) throws WriteException {
		writer.append(grammar.radioEnd());
		writer.appendLine(grammar.labelEnd());
	}

}
/*
 * JavaCC - OriginalChecksum=1f49b14ad67219d7d80b97f8500126cc (do not edit this
 * line)
 */
