/*
 * Generated By:JJTree: Do not edit this line. ASTRadiosInputDescription.java
 * Version 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Description;

public class ASTRadiosInputDescription extends Description {
	public ASTRadiosInputDescription(int id) {
		super(id);
	}

	public ASTRadiosInputDescription(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=73e2a7754f0cb3888168cee9b20507b2 (do not edit this
 * line)
 */
