/* Generated By:JJTree: Do not edit this line. ASTRadio.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import java.util.List;

import ro.swl.engine.parser.model.Component;
import ro.swl.engine.writer.TagWriter;
import ro.swl.engine.writer.WriteException;

public class ASTRadio extends Component {

	private boolean wrappedLabel;

	public ASTRadio(int id) {
		super(id);
	}

	@Override
	public void render(TagWriter writer) throws WriteException {
		if (!wrappedLabel) {
			ASTRadioLabel label = new ASTRadioLabel(0);
			label.jjtAddChild(this, 0);
			wrappedLabel = true;
			label.render(writer);
		} else {
			super.render(writer);
		}
	}

	@Override
	protected String getComponentName() {
		return grammar.radio();
	}

	@Override
	public void writeAttributes(TagWriter writer) throws WriteException {
		writer.append(grammar.radioType());
		writer.append(grammar.radioName(getGroupName()));
	}

	private String getGroupName() throws WriteException {
		List<String> modelVars = getImageOfChildNodesOfType(ASTModelVariable.class, true);

		if (modelVars.size() > 0) {
			return modelVars.get(0);
		} else {
			throw new WriteException("Cannot identify name of radio input.");
		}

	}

}
/*
 * JavaCC - OriginalChecksum=1f49b14ad67219d7d80b97f8500126cc (do not edit this
 * line)
 */
