/* Generated By:JJTree: Do not edit this line. ASTRadiosInputDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTRadiosInputDescription extends SWLNode {
  public ASTRadiosInputDescription(int id) {
    super(id);
  }

  public ASTRadiosInputDescription(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dd1431fbdef76337fc4317864e7ab2c5 (do not edit this line) */
