/*
 * Generated By:JJTree: Do not edit this line. ASTRadioInputDescription.java
 * Version 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Description;

public class ASTRadioInputDescription extends Description {
	public ASTRadioInputDescription(int id) {
		super(id);
	}

	public ASTRadioInputDescription(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=fb8cffd0ed794651bda55ce8c21b02d1 (do not edit this
 * line)
 */
