/* Generated By:JJTree: Do not edit this line. ASTSwdlFile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTSwdlFile extends SimpleNode {
  public ASTSwdlFile(int id) {
    super(id);
  }

  public ASTSwdlFile(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3681a88c6cd1bf545da4c7bc873cfb5 (do not edit this line) */
