/* Generated By:JJTree: Do not edit this line. ASTSelectbox.java Version 4.3 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Component;

public class ASTSelectbox extends Component {
	public ASTSelectbox(int id) {
		super(id);
	}

	public ASTSelectbox(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=553c4a1d1abc9d12dc92b17787467658 (do not edit this
 * line)
 */
