/* Generated By:JJTree: Do not edit this line. ASTScreenName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTScreenName extends SWLNode {
  public ASTScreenName(int id) {
    super(id);
  }

  public ASTScreenName(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c38bcd34c1ee5e0ad05a258f184f2a90 (do not edit this line) */
