/* Generated By:JJTree: Do not edit this line. ASTSelectOption.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTSelectOption extends SWLNode {
  public ASTSelectOption(int id) {
    super(id);
  }

  public ASTSelectOption(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=177ee2e5b86fc26ae3e25eb6a4bab050 (do not edit this line) */
