/*
 * Generated By:JJTree: Do not edit this line. ASTSelectInputDescription.java
 * Version 4.3
 */
/*
 * JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false
 * ,
 * NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true
 */
package ro.swl.engine.parser;

import ro.swl.engine.parser.model.Description;

public class ASTSelectInputDescription extends Description {
	public ASTSelectInputDescription(int id) {
		super(id);
	}

	public ASTSelectInputDescription(SWL p, int id) {
		super(p, id);
	}

}
/*
 * JavaCC - OriginalChecksum=590affc1dd63d583dc7791c65f04c6fc (do not edit this
 * line)
 */
