/* Generated By:JJTree: Do not edit this line. ASTScreen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTScreen extends SimpleNode {
  public ASTScreen(int id) {
    super(id);
  }

  public ASTScreen(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dcc0dac1b4be81f4ad5496c57f79d2e6 (do not edit this line) */
