/* Generated By:JJTree: Do not edit this line. ASTUi.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTUi extends SWLNode {
  public ASTUi(int id) {
    super(id);
  }

  public ASTUi(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=795c7838744d9883bead5d7528459a41 (do not edit this line) */
