/* Generated By:JJTree: Do not edit this line. ASTUl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.swl.engine.parser;

public
class ASTUl extends SimpleNode {
  public ASTUl(int id) {
    super(id);
  }

  public ASTUl(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8ce1d32813318904f497bb602dd829ba (do not edit this line) */
