/* Generated By:JJTree: Do not edit this line. ASTAppName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTAppName extends SimpleNode {
  public ASTAppName(int id) {
    super(id);
  }

  public ASTAppName(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6b03de5a330ac4d10ca47df6ccbd90cc (do not edit this line) */
