/* Generated By:JJTree: Do not edit this line. ASTBr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTBr extends SimpleNode {
  public ASTBr(int id) {
    super(id);
  }

  public ASTBr(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c2f435814b9398a485999d9dcbf324d6 (do not edit this line) */
