/* Generated By:JJTree: Do not edit this line. ASTCheckbox.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTCheckbox extends SimpleNode {
  public ASTCheckbox(int id) {
    super(id);
  }

  public ASTCheckbox(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb9de87179fa86bc1b8ea1d4e33c0e25 (do not edit this line) */
