/* Generated By:JJTree: Do not edit this line. ASTCssClassName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTCssClassName extends SimpleNode {
  public ASTCssClassName(int id) {
    super(id);
  }

  public ASTCssClassName(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1951eb27b3a7efee52ed3ff08b97363c (do not edit this line) */
