/* Generated By:JJTree: Do not edit this line. ASTController.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTController extends SimpleNode {
  public ASTController(int id) {
    super(id);
  }

  public ASTController(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=628c0da26aad671de9bdc54c403f2187 (do not edit this line) */
