/* Generated By:JJTree: Do not edit this line. ASTCssStyleValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTCssStyleValue extends SimpleNode {
  public ASTCssStyleValue(int id) {
    super(id);
  }

  public ASTCssStyleValue(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=288c8924446cd54041656ae7d866ce69 (do not edit this line) */
