/* Generated By:JJTree: Do not edit this line. ASTCssStyleName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTCssStyleName extends SimpleNode {
  public ASTCssStyleName(int id) {
    super(id);
  }

  public ASTCssStyleName(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6bcb6d9807ce939da7bcca021fcc7b92 (do not edit this line) */
