/* Generated By:JJTree: Do not edit this line. ASTCssStyle.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTCssStyle extends SimpleNode {
  public ASTCssStyle(int id) {
    super(id);
  }

  public ASTCssStyle(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0dd2ea2c3a31ce5589d4e3718f0e4dae (do not edit this line) */
