/* Generated By:JJTree: Do not edit this line. ASTH6.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTH6 extends SimpleNode {
  public ASTH6(int id) {
    super(id);
  }

  public ASTH6(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=400f63b31896a376dc4546ecb4215c71 (do not edit this line) */
