/* Generated By:JJTree: Do not edit this line. ASTH3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTH3 extends SimpleNode {
  public ASTH3(int id) {
    super(id);
  }

  public ASTH3(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a3587b4450256536aea273d7503993dc (do not edit this line) */
