/* Generated By:JJTree: Do not edit this line. ASTHorizontalLayoutDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTHorizontalLayoutDescription extends SimpleNode {
  public ASTHorizontalLayoutDescription(int id) {
    super(id);
  }

  public ASTHorizontalLayoutDescription(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=29533406edf90661f5090f2c2ff32104 (do not edit this line) */
