/* Generated By:JJTree: Do not edit this line. ASTH4.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTH4 extends SimpleNode {
  public ASTH4(int id) {
    super(id);
  }

  public ASTH4(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f3565b311f64648d0cae6f3ebfbbd2c1 (do not edit this line) */
