/* Generated By:JJTree: Do not edit this line. ASTHorizontalLayout.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTHorizontalLayout extends SimpleNode {
  public ASTHorizontalLayout(int id) {
    super(id);
  }

  public ASTHorizontalLayout(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5bdb5446c37e4b67ad85efa3f06dc60f (do not edit this line) */
