/* Generated By:JJTree: Do not edit this line. ASTLogic.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTLogic extends SimpleNode {
  public ASTLogic(int id) {
    super(id);
  }

  public ASTLogic(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=42ca86611952808cb758cd6934420911 (do not edit this line) */
