/* Generated By:JJTree: Do not edit this line. ASTModule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTModule extends SimpleNode {
  public ASTModule(int id) {
    super(id);
  }

  public ASTModule(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5a5b586c9b011fafd8e4ca70a24d95a0 (do not edit this line) */
