/* Generated By:JJTree: Do not edit this line. ASTModelVariable.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTModelVariable extends SimpleNode {
  public ASTModelVariable(int id) {
    super(id);
  }

  public ASTModelVariable(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ca29fe9d4b07cfca3b15e5e56ea2520c (do not edit this line) */
