/* Generated By:JJTree: Do not edit this line. ASTNameDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTNameDecl extends SimpleNode {
  public ASTNameDecl(int id) {
    super(id);
  }

  public ASTNameDecl(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5c6cd08741535de61a7a922eaa2ce93d (do not edit this line) */
