/* Generated By:JJTree: Do not edit this line. ASTRadio.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTRadio extends SimpleNode {
  public ASTRadio(int id) {
    super(id);
  }

  public ASTRadio(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=25258acf2e551ed3766c4d72c01bad14 (do not edit this line) */
