/* Generated By:JJTree: Do not edit this line. ASTRadioInputDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTRadioInputDescription extends SimpleNode {
  public ASTRadioInputDescription(int id) {
    super(id);
  }

  public ASTRadioInputDescription(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47a633e8d14224b66dd62718e4166366 (do not edit this line) */
