/* Generated By:JJTree: Do not edit this line. ASTSection.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTSection extends SimpleNode {
  public ASTSection(int id) {
    super(id);
  }

  public ASTSection(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b84ac26aad34aa8d234e065d286402ab (do not edit this line) */
