/* Generated By:JJTree: Do not edit this line. ASTScreen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTScreen extends SimpleNode {
  public ASTScreen(int id) {
    super(id);
  }

  public ASTScreen(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=61174db6bf79e7417ac04b80354fe846 (do not edit this line) */
