/* Generated By:JJTree: Do not edit this line. ASTSelectbox.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTSelectbox extends SimpleNode {
  public ASTSelectbox(int id) {
    super(id);
  }

  public ASTSelectbox(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dbb9bc2482cbb10611922ac66af79362 (do not edit this line) */
