/* Generated By:JJTree: Do not edit this line. ASTStdInputDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTStdInputDescription extends SimpleNode {
  public ASTStdInputDescription(int id) {
    super(id);
  }

  public ASTStdInputDescription(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=94ad3232e8f51c5210b1202a5640aaf3 (do not edit this line) */
