/* Generated By:JJTree: Do not edit this line. ASTSelectOptionGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTSelectOptionGroup extends SimpleNode {
  public ASTSelectOptionGroup(int id) {
    super(id);
  }

  public ASTSelectOptionGroup(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cf59f33bafe031166586f0bacba50a9f (do not edit this line) */
