/* Generated By:JJTree: Do not edit this line. ASTSwdlFile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTSwdlFile extends SimpleNode {
  public ASTSwdlFile(int id) {
    super(id);
  }

  public ASTSwdlFile(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9b39b2be62ad81aa123922e0965e5dd7 (do not edit this line) */
