/* Generated By:JJTree: Do not edit this line. ASTSelectOption.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTSelectOption extends SimpleNode {
  public ASTSelectOption(int id) {
    super(id);
  }

  public ASTSelectOption(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb248c053e0e84f78fdc0a60c9b0ec19 (do not edit this line) */
