/* Generated By:JJTree: Do not edit this line. ASTSelectInputDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTSelectInputDescription extends SimpleNode {
  public ASTSelectInputDescription(int id) {
    super(id);
  }

  public ASTSelectInputDescription(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ead97be91f399685f7673b5d02107596 (do not edit this line) */
