/* Generated By:JJTree: Do not edit this line. ASTScreenName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTScreenName extends SimpleNode {
  public ASTScreenName(int id) {
    super(id);
  }

  public ASTScreenName(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dee85e6e78f139ce6bfed2c02aefe0f8 (do not edit this line) */
