/* Generated By:JJTree: Do not edit this line. ASTVerticalLayout.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTVerticalLayout extends SimpleNode {
  public ASTVerticalLayout(int id) {
    super(id);
  }

  public ASTVerticalLayout(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aba9fa98551af79ac4084396a0fcd480 (do not edit this line) */
