/* Generated By:JJTree: Do not edit this line. ASTVerticalLayoutDescrition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTVerticalLayoutDescrition extends SimpleNode {
  public ASTVerticalLayoutDescrition(int id) {
    super(id);
  }

  public ASTVerticalLayoutDescrition(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=711e8231377062d7533a92a68deb81be (do not edit this line) */
