/* Generated By:JJTree: Do not edit this line. ASTVerticalLayoutDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ro.sft.recruiter;

public
class ASTVerticalLayoutDescription extends SimpleNode {
  public ASTVerticalLayoutDescription(int id) {
    super(id);
  }

  public ASTVerticalLayoutDescription(SWL p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d218d7aaa9248a4f7dde5ec5d8797622 (do not edit this line) */
