/* Generated By:JavaCC: Do not edit this line. SWLTreeConstants.java Version 5.0 */
package ro.sft.recruiter;

public interface SWLTreeConstants
{
  public int JJTSWDLFILE = 0;
  public int JJTNAMEDECL = 1;
  public int JJTAPPNAME = 2;
  public int JJTMODULE = 3;
  public int JJTMODULENAME = 4;
  public int JJTMODULEBODY = 5;
  public int JJTUI = 6;
  public int JJTSCREEN = 7;
  public int JJTSCREENNAME = 8;
  public int JJTMODEL = 9;
  public int JJTCONTROLLER = 10;
  public int JJTGENERICBLOCK = 11;
  public int JJTMVCAREA = 12;
  public int JJTCOMPONENT = 13;
  public int JJTVERTICALLAYOUT = 14;
  public int JJTHORIZONTALLAYOUT = 15;
  public int JJTHORIZONTALFORM = 16;
  public int JJTSECTION = 17;
  public int JJTBR = 18;
  public int JJTH1 = 19;
  public int JJTH2 = 20;
  public int JJTH3 = 21;
  public int JJTH4 = 22;
  public int JJTH5 = 23;
  public int JJTH6 = 24;
  public int JJTINPUT = 25;
  public int JJTINPUTFILE = 26;
  public int JJTINPUTAREA = 27;
  public int JJTCHECKBOX = 28;
  public int JJTSELECTBOX = 29;
  public int JJTRADIO = 30;
  public int JJTRADIOS = 31;
  public int JJTLABEL = 32;
  public int JJTIMG = 33;
  public int JJTMODELVARIABLE = 34;
  public int JJTVERTICALLAYOUTDESCRIPTION = 35;
  public int JJTHORIZONTALLAYOUTDESCRIPTION = 36;
  public int JJTCOLUMNDESCRIPTION = 37;
  public int JJTRADIOINPUTDESCRIPTION = 38;
  public int JJTRADIOSINPUTDESCRIPTION = 39;
  public int JJTSELECTINPUTDESCRIPTION = 40;
  public int JJTSELECTBOXOPTIONS = 41;
  public int JJTSELECTOPTION = 42;
  public int JJTSELECTOPTIONGROUP = 43;
  public int JJTSTDINPUTDESCRIPTION = 44;
  public int JJTCSSSTYLE = 45;
  public int JJTCSSCLASSNAME = 46;
  public int JJTCSSINLINESTYLE = 47;
  public int JJTCSSSTYLENAME = 48;
  public int JJTCSSSTYLEVALUE = 49;
  public int JJTLOGIC = 50;
  public int JJTDOMAIN = 51;


  public String[] jjtNodeName = {
    "SwdlFile",
    "NameDecl",
    "AppName",
    "Module",
    "ModuleName",
    "ModuleBody",
    "Ui",
    "Screen",
    "ScreenName",
    "Model",
    "Controller",
    "GenericBlock",
    "MvcArea",
    "Component",
    "VerticalLayout",
    "HorizontalLayout",
    "HorizontalForm",
    "Section",
    "Br",
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Input",
    "InputFile",
    "InputArea",
    "Checkbox",
    "Selectbox",
    "Radio",
    "Radios",
    "Label",
    "Img",
    "ModelVariable",
    "VerticalLayoutDescription",
    "HorizontalLayoutDescription",
    "ColumnDescription",
    "RadioInputDescription",
    "RadiosInputDescription",
    "SelectInputDescription",
    "SelectboxOptions",
    "SelectOption",
    "SelectOptionGroup",
    "StdInputDescription",
    "CssStyle",
    "CssClassName",
    "CssInlineStyle",
    "CssStyleName",
    "CssStyleValue",
    "Logic",
    "Domain",
  };
}
/* JavaCC - OriginalChecksum=c37744a5c97d5341b69accf9cd58537e (do not edit this line) */
